server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location /api/web/ {
    proxy_pass http://gateway-web:8090/api/web/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location = /health {
    proxy_pass http://gateway-web:8090/health;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location /mfe-auth/ {
    try_files $uri $uri/ /mfe-auth/index.html;
  }

  location /mfe-parking/ {
    try_files $uri $uri/ /mfe-parking/index.html;
  }

  location /mfe-reservations/ {
    try_files $uri $uri/ /mfe-reservations/index.html;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
